config/routes.rb
Rails.application.routes.draw do

  resources :otprecs, only: [:show, :index, :create] do
    member do
      post :show
      post 'destroy'
    end
  end

  root to: 'otprecs#index'

end

app/models/record.rb
class Record < ActiveRecord::Base
  validates :text, :url, :end_date, presence: true
  validates :url, format: { with: /[a-z0-9]{40}/, message: 'Wrong format of url !!' }
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/otprec_controller.rb
class OtprecController < ApplicationController
  def index
  end

  def create
    @record   = Record.new

    text      = params['myform']['text']
    delay     = params[:store_days].to_i
    salt      = params['myform']['salt']
    url       = Digest::SHA1.hexdigest("#{Time.now}#{([*('A'..'Z'),*('a'..'z'),*('0'..'9')]-%w(0 1 I O)).sample(32).join}")
  
    puts "SALT_raw is #{salt.inspect}"

    salt = ENV["SECRET_KEY_BASE"] if salt.nil? || salt.empty?
    if salt.nil?
      @msg='Admin have to use SECRET_KEY_BASE variable'
      return 
    end

    puts "SALT1 is #{salt}"

    begin
      cipher = OpenSSL::Cipher::Cipher.new("aes-256-cbc")
      cipher.encrypt
      cipher.key = Digest::SHA2.digest(salt.chomp)
      encrypted = cipher.update(text)
      encrypted << cipher.final
      encrypted = Base64.encode64(encrypted)
    rescue OpenSSL::CipherError => e
      @msg = "incorrect password"
    rescue Exception => e
      @msg = "unknown error"
    end
    @record.text      = encrypted
    @record.url       = url
    @record.end_date  = delay.days.from_now

    if @record.save
      original_url = request.original_url
      url_parts = original_url.split('/')[0...-1]
      new_url = url_parts.join('/')+'/'+url
      @msg = new_url
    else
      flash[:error] = "Unable to save your password, please try again without hacks" 
      redirect_to root_url
    end
  end

  def show
    url   = params[:url]
    salt  = params[:salt]
    salt = ENV["SECRET_KEY_BASE"] if salt.nil? || salt.empty?
    puts "SALT2 is #{salt}"

    record = Record.find_by! url: url
    if record && record.end_date > Time.now
      begin
        encrypted = Base64.decode64(record.text)
        cipher = OpenSSL::Cipher::Cipher.new("aes-256-cbc")
        cipher.decrypt
        cipher.key = Digest::SHA2.digest(salt.chomp)
        text = cipher.update(encrypted)
        text << cipher.final 
        @msg = text
        record.destroy
      rescue OpenSSL::Cipher::CipherError => e
        @msg = "incorrect password"
      rescue Exception => e
        @msg = "unknown error"
      end
    else
      record.destroy
      flash[:error] = "Message wasn't found" 
      redirect_to root_url
    end
    rescue ActiveRecord::RecordNotFound
      flash[:error] = "Message wasn't found" 
      redirect_to root_url
  end
end

app/controllers/otprecs_controller.rb
class OtprecsController < ApplicationController
  def index
  end

  def create
    @record   = Record.new

    text      = params['text']
    delay     = params['store_days'].to_i
    id        = Digest::SHA256.hexdigest("#{Time.now}#{([*('A'..'Z'), *('a'..'z'), *('0'..'9')] - %w(0 1 I O)).sample(32).join}")

    @record.text      = text
    @record.url       = id
    @record.end_date  = delay.days.from_now

    if @record.save
      @msg = "#{otprecs_url}/#{id}"
    else
      flash[:error] = 'Unable to save message, please try again without later'
      redirect_to root_url
    end
  end

  def show
    url = params[:id]
    if params.key?('myform')
      passphrase = params['myform']['passphrase']
    end
    passphrase = ENV['SECRET_KEY_BASE'] if passphrase.nil? || passphrase.empty?

    record = Record.find_by! url: url
    if record && record.end_date > Time.now
      @msg = record.text
    else
      record.destroy
      flash[:error] = "Message was removed because it's too old"
      redirect_to root_url
    end
    rescue ActiveRecord::RecordNotFound
      flash[:error] = "Message wasn't found"
      redirect_to root_url
  end

  def destroy
    url = params[:id]
    record = Record.find_by! url: url
    record.destroy
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/otprec_helper.rb
module OtprecHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Otprec</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>
  <% flash.each do |name, msg| -%>
    <%= content_tag :div, msg, class: 'pure-alert-warning' %>
  <% end -%>
<div class="container">
  <div class="body">
    <%= yield %>
  </div>
  <div class="footer">
    <div class="center">
       For trusting this site you could take a look at source code in the <a href="https://github.com/alter/otprec.git">github</a>
    </div>
  </div>
</div>
</body>
</html>

app/views/otprec/index.html.erb
<h1>OneTimeMessage</h1>
<%= form_tag otprec_create_path, html: {:class => 'pure-form pure-form-stacked'} do %>
  <div class="pure-control-group">
  <%= text_area :myform, :text, :placeholder => 'Type message here...', :cols => 100, :rows => 10  %>
  </div>
  <div class="pure-control-group">
  <%= text_area :myform, :salt, :placeholder => 'Type passphrase here for encrypting message here...', :cols =>100, :rows => 1 %>
  </div>
  <div class="pure-control-group">
  <%= label_tag "How many days store this link" %>
  <%= number_field_tag :store_days, nil, in: 1..31, step: 1, :value => 1 %>
  <div class="pure-control-group">
  <%= submit_tag "Save", :class => 'pure-button pure-button-primary' %>
  </div>
<% end %>

app/views/otprecs/create.html.erb
<h1>OneTimePassword</h1>
<%= javascript_tag do %>
  copyToClipboard("<%= @msg %>");
<% end %>
<%= @msg %>
<br/>
<%= link_to 'Create new record', root_url %>

app/views/otprecs/destroy.html.erb
Message was removed

app/views/otprecs/index.html.erb
<h1>OneTimePassword</h1>
<%= form_tag otprecs_path, html: {:class => 'pure-form pure-form-stacked'} do %>
  <div class="pure-control-group">
  <%= text_area :myform, :text, :placeholder => 'Type message here...', :cols => 100, :rows => 10  %>
  </div>
  <div class="pure-control-group">
  <%= text_field :myform, :passphrase, :placeholder => 'Type passphrase here for encrypting message here...', :size =>100 %>
  </div>
  <div class="pure-control-group">
  <%= label_tag "Storage time" %>
  <%= number_field_tag :store_days, nil, in: 1..31, step: 1, :value => 1 %>
  <%= label_tag "day(s)" %>
  <div class="pure-control-group">
    <input type="button" onclick="javascript:void(0)" class="subclick pure-button pure-button-primary" value="Save"/>
  </div>
<% end %>

<%= javascript_tag do %>
  document.getElementById("myform_text").select();
<% end %>

app/views/otprecs/show.html.erb
<h1>OneTimePassword</h1>
<pre>
<div id="message"></div>
</pre>
<%= javascript_tag do %>
  var key = prompt("Please enter message key");
  var message = "<%= @msg.html_safe %>";
  try {
    decrypted = CryptoJS.AES.decrypt(message, key);
    decrypted_msg = decrypted.toString(CryptoJS.enc.Utf8);
  } catch( e ) {
    alert( e );
  } finally {
    $('#message').text(decrypted_msg);
    if( decrypted_msg ){
      $.post(document.URL+'/destroy');
    }
  }
<% end %>